title: DLC Inference Speed Benchmark
description: A database of inference speed benchmark results on various video sizes, platforms and architectures
theme: minima

github_username: deeplabcut

exclude:
  - Gemfile
  - Gemfile.lock
  - "**README.md"
